/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export interface CreateCartDto {
  /** Total value of cart */
  totalValue: number;
  /** Products */
  products: string;
  /** User id */
  userId: string;
}
