/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /** User name */
  name: string;
  /** User email */
  email: string;
  /** User password */
  password: string;
}
