/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export interface OutputAddressDto {
  /** Address id */
  id: string;
  /** City */
  city: string;
  /** Country */
  country: string;
  /** Full Name */
  fullName: string;
  /** Line One */
  lineOne: string;
  /** Line Two */
  lineTwo: string;
  /** State or Region */
  stateOrRegion: string;
  /** Zip Code */
  zipCpde: string;
  /** Created At */
  createdAt: string;
}
