/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export const OutputOrderDtoValue = { [key: string]: unknown } as const;
export type OutputOrderDto = typeof OutputOrderDtoValue;
