/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export interface OutputUserDto {
  /** User id */
  id: string;
  /** User name */
  name: string;
  /** User email */
  email: string;
  /** User creation date */
  createdAt: string;
}
