/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export interface OutputCartDto {
  /** Cart id */
  id: string;
  /** Total value of cart */
  totalValue: number;
  /** Products */
  products: string;
  /** User id */
  userId: string;
  /** Cart creation date */
  createdAt: string;
}
