/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */

export interface UpdateProductDto {
  /** Product name */
  name?: string;
  /** Product starts */
  starts?: number;
  /** Product colors */
  colors?: string;
  /** Product price */
  price?: number;
  /** Product image url */
  imageUrl?: string;
}
