/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Teste mobile
 * API para o teste mobile
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';

export interface UpdateOrderDto {
  /** Payment method */
  paymentMethod?: string;
  /** Cart id */
  cartId?: string;
  /** Address id */
  addressId?: string;
  /** Address */
  shippingAddress?: Address;
}
